// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kongken/ohome/internal/dao/ent/community"
	"github.com/kongken/ohome/internal/dao/ent/predicate"
)

// CommunityUpdate is the builder for updating Community entities.
type CommunityUpdate struct {
	config
	hooks    []Hook
	mutation *CommunityMutation
}

// Where appends a list predicates to the CommunityUpdate builder.
func (_u *CommunityUpdate) Where(ps ...predicate.Community) *CommunityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CommunityUpdate) SetName(v string) *CommunityUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CommunityUpdate) SetNillableName(v *string) *CommunityUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CommunityUpdate) SetDescription(v string) *CommunityUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CommunityUpdate) SetNillableDescription(v *string) *CommunityUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CommunityUpdate) ClearDescription() *CommunityUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetIconURL sets the "icon_url" field.
func (_u *CommunityUpdate) SetIconURL(v string) *CommunityUpdate {
	_u.mutation.SetIconURL(v)
	return _u
}

// SetNillableIconURL sets the "icon_url" field if the given value is not nil.
func (_u *CommunityUpdate) SetNillableIconURL(v *string) *CommunityUpdate {
	if v != nil {
		_u.SetIconURL(*v)
	}
	return _u
}

// ClearIconURL clears the value of the "icon_url" field.
func (_u *CommunityUpdate) ClearIconURL() *CommunityUpdate {
	_u.mutation.ClearIconURL()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *CommunityUpdate) SetCoverURL(v string) *CommunityUpdate {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *CommunityUpdate) SetNillableCoverURL(v *string) *CommunityUpdate {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *CommunityUpdate) ClearCoverURL() *CommunityUpdate {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetCategory sets the "category" field.
func (_u *CommunityUpdate) SetCategory(v string) *CommunityUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *CommunityUpdate) SetNillableCategory(v *string) *CommunityUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *CommunityUpdate) ClearCategory() *CommunityUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetMembersCount sets the "members_count" field.
func (_u *CommunityUpdate) SetMembersCount(v int) *CommunityUpdate {
	_u.mutation.ResetMembersCount()
	_u.mutation.SetMembersCount(v)
	return _u
}

// SetNillableMembersCount sets the "members_count" field if the given value is not nil.
func (_u *CommunityUpdate) SetNillableMembersCount(v *int) *CommunityUpdate {
	if v != nil {
		_u.SetMembersCount(*v)
	}
	return _u
}

// AddMembersCount adds value to the "members_count" field.
func (_u *CommunityUpdate) AddMembersCount(v int) *CommunityUpdate {
	_u.mutation.AddMembersCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommunityUpdate) SetUpdatedAt(v time.Time) *CommunityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CommunityMutation object of the builder.
func (_u *CommunityUpdate) Mutation() *CommunityMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommunityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommunityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommunityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommunityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommunityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := community.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommunityUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := community.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Community.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := community.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Community.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MembersCount(); ok {
		if err := community.MembersCountValidator(v); err != nil {
			return &ValidationError{Name: "members_count", err: fmt.Errorf(`ent: validator failed for field "Community.members_count": %w`, err)}
		}
	}
	return nil
}

func (_u *CommunityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(community.Table, community.Columns, sqlgraph.NewFieldSpec(community.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(community.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(community.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(community.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IconURL(); ok {
		_spec.SetField(community.FieldIconURL, field.TypeString, value)
	}
	if _u.mutation.IconURLCleared() {
		_spec.ClearField(community.FieldIconURL, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(community.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(community.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(community.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(community.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.MembersCount(); ok {
		_spec.SetField(community.FieldMembersCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMembersCount(); ok {
		_spec.AddField(community.FieldMembersCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(community.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{community.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommunityUpdateOne is the builder for updating a single Community entity.
type CommunityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommunityMutation
}

// SetName sets the "name" field.
func (_u *CommunityUpdateOne) SetName(v string) *CommunityUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CommunityUpdateOne) SetNillableName(v *string) *CommunityUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CommunityUpdateOne) SetDescription(v string) *CommunityUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CommunityUpdateOne) SetNillableDescription(v *string) *CommunityUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CommunityUpdateOne) ClearDescription() *CommunityUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetIconURL sets the "icon_url" field.
func (_u *CommunityUpdateOne) SetIconURL(v string) *CommunityUpdateOne {
	_u.mutation.SetIconURL(v)
	return _u
}

// SetNillableIconURL sets the "icon_url" field if the given value is not nil.
func (_u *CommunityUpdateOne) SetNillableIconURL(v *string) *CommunityUpdateOne {
	if v != nil {
		_u.SetIconURL(*v)
	}
	return _u
}

// ClearIconURL clears the value of the "icon_url" field.
func (_u *CommunityUpdateOne) ClearIconURL() *CommunityUpdateOne {
	_u.mutation.ClearIconURL()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *CommunityUpdateOne) SetCoverURL(v string) *CommunityUpdateOne {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *CommunityUpdateOne) SetNillableCoverURL(v *string) *CommunityUpdateOne {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *CommunityUpdateOne) ClearCoverURL() *CommunityUpdateOne {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetCategory sets the "category" field.
func (_u *CommunityUpdateOne) SetCategory(v string) *CommunityUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *CommunityUpdateOne) SetNillableCategory(v *string) *CommunityUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *CommunityUpdateOne) ClearCategory() *CommunityUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetMembersCount sets the "members_count" field.
func (_u *CommunityUpdateOne) SetMembersCount(v int) *CommunityUpdateOne {
	_u.mutation.ResetMembersCount()
	_u.mutation.SetMembersCount(v)
	return _u
}

// SetNillableMembersCount sets the "members_count" field if the given value is not nil.
func (_u *CommunityUpdateOne) SetNillableMembersCount(v *int) *CommunityUpdateOne {
	if v != nil {
		_u.SetMembersCount(*v)
	}
	return _u
}

// AddMembersCount adds value to the "members_count" field.
func (_u *CommunityUpdateOne) AddMembersCount(v int) *CommunityUpdateOne {
	_u.mutation.AddMembersCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommunityUpdateOne) SetUpdatedAt(v time.Time) *CommunityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CommunityMutation object of the builder.
func (_u *CommunityUpdateOne) Mutation() *CommunityMutation {
	return _u.mutation
}

// Where appends a list predicates to the CommunityUpdate builder.
func (_u *CommunityUpdateOne) Where(ps ...predicate.Community) *CommunityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommunityUpdateOne) Select(field string, fields ...string) *CommunityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Community entity.
func (_u *CommunityUpdateOne) Save(ctx context.Context) (*Community, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommunityUpdateOne) SaveX(ctx context.Context) *Community {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommunityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommunityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommunityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := community.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommunityUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := community.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Community.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := community.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Community.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MembersCount(); ok {
		if err := community.MembersCountValidator(v); err != nil {
			return &ValidationError{Name: "members_count", err: fmt.Errorf(`ent: validator failed for field "Community.members_count": %w`, err)}
		}
	}
	return nil
}

func (_u *CommunityUpdateOne) sqlSave(ctx context.Context) (_node *Community, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(community.Table, community.Columns, sqlgraph.NewFieldSpec(community.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Community.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, community.FieldID)
		for _, f := range fields {
			if !community.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != community.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(community.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(community.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(community.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IconURL(); ok {
		_spec.SetField(community.FieldIconURL, field.TypeString, value)
	}
	if _u.mutation.IconURLCleared() {
		_spec.ClearField(community.FieldIconURL, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(community.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(community.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(community.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(community.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.MembersCount(); ok {
		_spec.SetField(community.FieldMembersCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMembersCount(); ok {
		_spec.AddField(community.FieldMembersCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(community.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Community{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{community.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
