// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: discovery/v1/discovery.proto

package discoveryv1

import (
	context "context"
	v11 "github.com/kongken/ohome/pkg/proto/communities/v1"
	v1 "github.com/kongken/ohome/pkg/proto/posts/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiscoveryService_GetHighlights_FullMethodName        = "/discovery.v1.DiscoveryService/GetHighlights"
	DiscoveryService_TrendingPosts_FullMethodName        = "/discovery.v1.DiscoveryService/TrendingPosts"
	DiscoveryService_TrendingTopics_FullMethodName       = "/discovery.v1.DiscoveryService/TrendingTopics"
	DiscoveryService_SuggestedUsers_FullMethodName       = "/discovery.v1.DiscoveryService/SuggestedUsers"
	DiscoveryService_SuggestedCommunities_FullMethodName = "/discovery.v1.DiscoveryService/SuggestedCommunities"
	DiscoveryService_LiveDiscussions_FullMethodName      = "/discovery.v1.DiscoveryService/LiveDiscussions"
	DiscoveryService_Categories_FullMethodName           = "/discovery.v1.DiscoveryService/Categories"
	DiscoveryService_Search_FullMethodName               = "/discovery.v1.DiscoveryService/Search"
	DiscoveryService_Suggest_FullMethodName              = "/discovery.v1.DiscoveryService/Suggest"
)

// DiscoveryServiceClient is the client API for DiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DiscoveryService powers the Discovery screen and global search.
//
// HTTP mapping (see api.md §7):
//
//	GET /api/v1/discover/highlights
//	GET /api/v1/discover/trending/posts
//	GET /api/v1/discover/trending/topics
//	GET /api/v1/discover/suggested-users
//	GET /api/v1/discover/communities
//	GET /api/v1/discover/discussions
//	GET /api/v1/discover/categories
//	GET /api/v1/search
//	GET /api/v1/search/suggest
type DiscoveryServiceClient interface {
	GetHighlights(ctx context.Context, in *GetHighlightsRequest, opts ...grpc.CallOption) (*GetHighlightsResponse, error)
	TrendingPosts(ctx context.Context, in *TrendingPostsRequest, opts ...grpc.CallOption) (*v1.ListPostsResponse, error)
	TrendingTopics(ctx context.Context, in *TrendingTopicsRequest, opts ...grpc.CallOption) (*TrendingTopicsResponse, error)
	SuggestedUsers(ctx context.Context, in *SuggestedUsersRequest, opts ...grpc.CallOption) (*SuggestedUsersResponse, error)
	SuggestedCommunities(ctx context.Context, in *SuggestedCommunitiesRequest, opts ...grpc.CallOption) (*v11.ListCommunitiesResponse, error)
	LiveDiscussions(ctx context.Context, in *LiveDiscussionsRequest, opts ...grpc.CallOption) (*LiveDiscussionsResponse, error)
	Categories(ctx context.Context, in *CategoriesRequest, opts ...grpc.CallOption) (*CategoriesResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Suggest(ctx context.Context, in *SuggestRequest, opts ...grpc.CallOption) (*SuggestResponse, error)
}

type discoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryServiceClient(cc grpc.ClientConnInterface) DiscoveryServiceClient {
	return &discoveryServiceClient{cc}
}

func (c *discoveryServiceClient) GetHighlights(ctx context.Context, in *GetHighlightsRequest, opts ...grpc.CallOption) (*GetHighlightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHighlightsResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_GetHighlights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) TrendingPosts(ctx context.Context, in *TrendingPostsRequest, opts ...grpc.CallOption) (*v1.ListPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListPostsResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_TrendingPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) TrendingTopics(ctx context.Context, in *TrendingTopicsRequest, opts ...grpc.CallOption) (*TrendingTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrendingTopicsResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_TrendingTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) SuggestedUsers(ctx context.Context, in *SuggestedUsersRequest, opts ...grpc.CallOption) (*SuggestedUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestedUsersResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_SuggestedUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) SuggestedCommunities(ctx context.Context, in *SuggestedCommunitiesRequest, opts ...grpc.CallOption) (*v11.ListCommunitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.ListCommunitiesResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_SuggestedCommunities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) LiveDiscussions(ctx context.Context, in *LiveDiscussionsRequest, opts ...grpc.CallOption) (*LiveDiscussionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LiveDiscussionsResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_LiveDiscussions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) Categories(ctx context.Context, in *CategoriesRequest, opts ...grpc.CallOption) (*CategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoriesResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_Categories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) Suggest(ctx context.Context, in *SuggestRequest, opts ...grpc.CallOption) (*SuggestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_Suggest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServiceServer is the server API for DiscoveryService service.
// All implementations must embed UnimplementedDiscoveryServiceServer
// for forward compatibility.
//
// DiscoveryService powers the Discovery screen and global search.
//
// HTTP mapping (see api.md §7):
//
//	GET /api/v1/discover/highlights
//	GET /api/v1/discover/trending/posts
//	GET /api/v1/discover/trending/topics
//	GET /api/v1/discover/suggested-users
//	GET /api/v1/discover/communities
//	GET /api/v1/discover/discussions
//	GET /api/v1/discover/categories
//	GET /api/v1/search
//	GET /api/v1/search/suggest
type DiscoveryServiceServer interface {
	GetHighlights(context.Context, *GetHighlightsRequest) (*GetHighlightsResponse, error)
	TrendingPosts(context.Context, *TrendingPostsRequest) (*v1.ListPostsResponse, error)
	TrendingTopics(context.Context, *TrendingTopicsRequest) (*TrendingTopicsResponse, error)
	SuggestedUsers(context.Context, *SuggestedUsersRequest) (*SuggestedUsersResponse, error)
	SuggestedCommunities(context.Context, *SuggestedCommunitiesRequest) (*v11.ListCommunitiesResponse, error)
	LiveDiscussions(context.Context, *LiveDiscussionsRequest) (*LiveDiscussionsResponse, error)
	Categories(context.Context, *CategoriesRequest) (*CategoriesResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	Suggest(context.Context, *SuggestRequest) (*SuggestResponse, error)
	mustEmbedUnimplementedDiscoveryServiceServer()
}

// UnimplementedDiscoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryServiceServer struct{}

func (UnimplementedDiscoveryServiceServer) GetHighlights(context.Context, *GetHighlightsRequest) (*GetHighlightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHighlights not implemented")
}
func (UnimplementedDiscoveryServiceServer) TrendingPosts(context.Context, *TrendingPostsRequest) (*v1.ListPostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrendingPosts not implemented")
}
func (UnimplementedDiscoveryServiceServer) TrendingTopics(context.Context, *TrendingTopicsRequest) (*TrendingTopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrendingTopics not implemented")
}
func (UnimplementedDiscoveryServiceServer) SuggestedUsers(context.Context, *SuggestedUsersRequest) (*SuggestedUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuggestedUsers not implemented")
}
func (UnimplementedDiscoveryServiceServer) SuggestedCommunities(context.Context, *SuggestedCommunitiesRequest) (*v11.ListCommunitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuggestedCommunities not implemented")
}
func (UnimplementedDiscoveryServiceServer) LiveDiscussions(context.Context, *LiveDiscussionsRequest) (*LiveDiscussionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LiveDiscussions not implemented")
}
func (UnimplementedDiscoveryServiceServer) Categories(context.Context, *CategoriesRequest) (*CategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Categories not implemented")
}
func (UnimplementedDiscoveryServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedDiscoveryServiceServer) Suggest(context.Context, *SuggestRequest) (*SuggestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Suggest not implemented")
}
func (UnimplementedDiscoveryServiceServer) mustEmbedUnimplementedDiscoveryServiceServer() {}
func (UnimplementedDiscoveryServiceServer) testEmbeddedByValue()                          {}

// UnsafeDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServiceServer will
// result in compilation errors.
type UnsafeDiscoveryServiceServer interface {
	mustEmbedUnimplementedDiscoveryServiceServer()
}

func RegisterDiscoveryServiceServer(s grpc.ServiceRegistrar, srv DiscoveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryService_ServiceDesc, srv)
}

func _DiscoveryService_GetHighlights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHighlightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).GetHighlights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_GetHighlights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).GetHighlights(ctx, req.(*GetHighlightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_TrendingPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrendingPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).TrendingPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_TrendingPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).TrendingPosts(ctx, req.(*TrendingPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_TrendingTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrendingTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).TrendingTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_TrendingTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).TrendingTopics(ctx, req.(*TrendingTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_SuggestedUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestedUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).SuggestedUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_SuggestedUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).SuggestedUsers(ctx, req.(*SuggestedUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_SuggestedCommunities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestedCommunitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).SuggestedCommunities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_SuggestedCommunities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).SuggestedCommunities(ctx, req.(*SuggestedCommunitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_LiveDiscussions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiveDiscussionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).LiveDiscussions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_LiveDiscussions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).LiveDiscussions(ctx, req.(*LiveDiscussionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_Categories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).Categories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_Categories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).Categories(ctx, req.(*CategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_Suggest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).Suggest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_Suggest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).Suggest(ctx, req.(*SuggestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoveryService_ServiceDesc is the grpc.ServiceDesc for DiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discovery.v1.DiscoveryService",
	HandlerType: (*DiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHighlights",
			Handler:    _DiscoveryService_GetHighlights_Handler,
		},
		{
			MethodName: "TrendingPosts",
			Handler:    _DiscoveryService_TrendingPosts_Handler,
		},
		{
			MethodName: "TrendingTopics",
			Handler:    _DiscoveryService_TrendingTopics_Handler,
		},
		{
			MethodName: "SuggestedUsers",
			Handler:    _DiscoveryService_SuggestedUsers_Handler,
		},
		{
			MethodName: "SuggestedCommunities",
			Handler:    _DiscoveryService_SuggestedCommunities_Handler,
		},
		{
			MethodName: "LiveDiscussions",
			Handler:    _DiscoveryService_LiveDiscussions_Handler,
		},
		{
			MethodName: "Categories",
			Handler:    _DiscoveryService_Categories_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _DiscoveryService_Search_Handler,
		},
		{
			MethodName: "Suggest",
			Handler:    _DiscoveryService_Suggest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery/v1/discovery.proto",
}
