// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: messages/v1/messages.proto

package messagesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kongken/ohome/pkg/proto/messages/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MessageServiceName is the fully-qualified name of the MessageService service.
	MessageServiceName = "messages.v1.MessageService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MessageServiceListConversationsProcedure is the fully-qualified name of the MessageService's
	// ListConversations RPC.
	MessageServiceListConversationsProcedure = "/messages.v1.MessageService/ListConversations"
	// MessageServiceCreateConversationProcedure is the fully-qualified name of the MessageService's
	// CreateConversation RPC.
	MessageServiceCreateConversationProcedure = "/messages.v1.MessageService/CreateConversation"
	// MessageServiceGetConversationProcedure is the fully-qualified name of the MessageService's
	// GetConversation RPC.
	MessageServiceGetConversationProcedure = "/messages.v1.MessageService/GetConversation"
	// MessageServiceListMessagesProcedure is the fully-qualified name of the MessageService's
	// ListMessages RPC.
	MessageServiceListMessagesProcedure = "/messages.v1.MessageService/ListMessages"
	// MessageServiceSendMessageProcedure is the fully-qualified name of the MessageService's
	// SendMessage RPC.
	MessageServiceSendMessageProcedure = "/messages.v1.MessageService/SendMessage"
	// MessageServiceMarkReadProcedure is the fully-qualified name of the MessageService's MarkRead RPC.
	MessageServiceMarkReadProcedure = "/messages.v1.MessageService/MarkRead"
	// MessageServiceDeleteMessageProcedure is the fully-qualified name of the MessageService's
	// DeleteMessage RPC.
	MessageServiceDeleteMessageProcedure = "/messages.v1.MessageService/DeleteMessage"
)

// MessageServiceClient is a client for the messages.v1.MessageService service.
type MessageServiceClient interface {
	ListConversations(context.Context, *connect.Request[v1.ListConversationsRequest]) (*connect.Response[v1.ListConversationsResponse], error)
	CreateConversation(context.Context, *connect.Request[v1.CreateConversationRequest]) (*connect.Response[v1.Conversation], error)
	GetConversation(context.Context, *connect.Request[v1.GetConversationRequest]) (*connect.Response[v1.Conversation], error)
	ListMessages(context.Context, *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error)
	SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.Message], error)
	MarkRead(context.Context, *connect.Request[v1.MarkReadRequest]) (*connect.Response[v1.MarkReadResponse], error)
	DeleteMessage(context.Context, *connect.Request[v1.DeleteMessageRequest]) (*connect.Response[v1.DeleteMessageResponse], error)
}

// NewMessageServiceClient constructs a client for the messages.v1.MessageService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMessageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MessageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	messageServiceMethods := v1.File_messages_v1_messages_proto.Services().ByName("MessageService").Methods()
	return &messageServiceClient{
		listConversations: connect.NewClient[v1.ListConversationsRequest, v1.ListConversationsResponse](
			httpClient,
			baseURL+MessageServiceListConversationsProcedure,
			connect.WithSchema(messageServiceMethods.ByName("ListConversations")),
			connect.WithClientOptions(opts...),
		),
		createConversation: connect.NewClient[v1.CreateConversationRequest, v1.Conversation](
			httpClient,
			baseURL+MessageServiceCreateConversationProcedure,
			connect.WithSchema(messageServiceMethods.ByName("CreateConversation")),
			connect.WithClientOptions(opts...),
		),
		getConversation: connect.NewClient[v1.GetConversationRequest, v1.Conversation](
			httpClient,
			baseURL+MessageServiceGetConversationProcedure,
			connect.WithSchema(messageServiceMethods.ByName("GetConversation")),
			connect.WithClientOptions(opts...),
		),
		listMessages: connect.NewClient[v1.ListMessagesRequest, v1.ListMessagesResponse](
			httpClient,
			baseURL+MessageServiceListMessagesProcedure,
			connect.WithSchema(messageServiceMethods.ByName("ListMessages")),
			connect.WithClientOptions(opts...),
		),
		sendMessage: connect.NewClient[v1.SendMessageRequest, v1.Message](
			httpClient,
			baseURL+MessageServiceSendMessageProcedure,
			connect.WithSchema(messageServiceMethods.ByName("SendMessage")),
			connect.WithClientOptions(opts...),
		),
		markRead: connect.NewClient[v1.MarkReadRequest, v1.MarkReadResponse](
			httpClient,
			baseURL+MessageServiceMarkReadProcedure,
			connect.WithSchema(messageServiceMethods.ByName("MarkRead")),
			connect.WithClientOptions(opts...),
		),
		deleteMessage: connect.NewClient[v1.DeleteMessageRequest, v1.DeleteMessageResponse](
			httpClient,
			baseURL+MessageServiceDeleteMessageProcedure,
			connect.WithSchema(messageServiceMethods.ByName("DeleteMessage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// messageServiceClient implements MessageServiceClient.
type messageServiceClient struct {
	listConversations  *connect.Client[v1.ListConversationsRequest, v1.ListConversationsResponse]
	createConversation *connect.Client[v1.CreateConversationRequest, v1.Conversation]
	getConversation    *connect.Client[v1.GetConversationRequest, v1.Conversation]
	listMessages       *connect.Client[v1.ListMessagesRequest, v1.ListMessagesResponse]
	sendMessage        *connect.Client[v1.SendMessageRequest, v1.Message]
	markRead           *connect.Client[v1.MarkReadRequest, v1.MarkReadResponse]
	deleteMessage      *connect.Client[v1.DeleteMessageRequest, v1.DeleteMessageResponse]
}

// ListConversations calls messages.v1.MessageService.ListConversations.
func (c *messageServiceClient) ListConversations(ctx context.Context, req *connect.Request[v1.ListConversationsRequest]) (*connect.Response[v1.ListConversationsResponse], error) {
	return c.listConversations.CallUnary(ctx, req)
}

// CreateConversation calls messages.v1.MessageService.CreateConversation.
func (c *messageServiceClient) CreateConversation(ctx context.Context, req *connect.Request[v1.CreateConversationRequest]) (*connect.Response[v1.Conversation], error) {
	return c.createConversation.CallUnary(ctx, req)
}

// GetConversation calls messages.v1.MessageService.GetConversation.
func (c *messageServiceClient) GetConversation(ctx context.Context, req *connect.Request[v1.GetConversationRequest]) (*connect.Response[v1.Conversation], error) {
	return c.getConversation.CallUnary(ctx, req)
}

// ListMessages calls messages.v1.MessageService.ListMessages.
func (c *messageServiceClient) ListMessages(ctx context.Context, req *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error) {
	return c.listMessages.CallUnary(ctx, req)
}

// SendMessage calls messages.v1.MessageService.SendMessage.
func (c *messageServiceClient) SendMessage(ctx context.Context, req *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.Message], error) {
	return c.sendMessage.CallUnary(ctx, req)
}

// MarkRead calls messages.v1.MessageService.MarkRead.
func (c *messageServiceClient) MarkRead(ctx context.Context, req *connect.Request[v1.MarkReadRequest]) (*connect.Response[v1.MarkReadResponse], error) {
	return c.markRead.CallUnary(ctx, req)
}

// DeleteMessage calls messages.v1.MessageService.DeleteMessage.
func (c *messageServiceClient) DeleteMessage(ctx context.Context, req *connect.Request[v1.DeleteMessageRequest]) (*connect.Response[v1.DeleteMessageResponse], error) {
	return c.deleteMessage.CallUnary(ctx, req)
}

// MessageServiceHandler is an implementation of the messages.v1.MessageService service.
type MessageServiceHandler interface {
	ListConversations(context.Context, *connect.Request[v1.ListConversationsRequest]) (*connect.Response[v1.ListConversationsResponse], error)
	CreateConversation(context.Context, *connect.Request[v1.CreateConversationRequest]) (*connect.Response[v1.Conversation], error)
	GetConversation(context.Context, *connect.Request[v1.GetConversationRequest]) (*connect.Response[v1.Conversation], error)
	ListMessages(context.Context, *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error)
	SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.Message], error)
	MarkRead(context.Context, *connect.Request[v1.MarkReadRequest]) (*connect.Response[v1.MarkReadResponse], error)
	DeleteMessage(context.Context, *connect.Request[v1.DeleteMessageRequest]) (*connect.Response[v1.DeleteMessageResponse], error)
}

// NewMessageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMessageServiceHandler(svc MessageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	messageServiceMethods := v1.File_messages_v1_messages_proto.Services().ByName("MessageService").Methods()
	messageServiceListConversationsHandler := connect.NewUnaryHandler(
		MessageServiceListConversationsProcedure,
		svc.ListConversations,
		connect.WithSchema(messageServiceMethods.ByName("ListConversations")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceCreateConversationHandler := connect.NewUnaryHandler(
		MessageServiceCreateConversationProcedure,
		svc.CreateConversation,
		connect.WithSchema(messageServiceMethods.ByName("CreateConversation")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceGetConversationHandler := connect.NewUnaryHandler(
		MessageServiceGetConversationProcedure,
		svc.GetConversation,
		connect.WithSchema(messageServiceMethods.ByName("GetConversation")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceListMessagesHandler := connect.NewUnaryHandler(
		MessageServiceListMessagesProcedure,
		svc.ListMessages,
		connect.WithSchema(messageServiceMethods.ByName("ListMessages")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceSendMessageHandler := connect.NewUnaryHandler(
		MessageServiceSendMessageProcedure,
		svc.SendMessage,
		connect.WithSchema(messageServiceMethods.ByName("SendMessage")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceMarkReadHandler := connect.NewUnaryHandler(
		MessageServiceMarkReadProcedure,
		svc.MarkRead,
		connect.WithSchema(messageServiceMethods.ByName("MarkRead")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceDeleteMessageHandler := connect.NewUnaryHandler(
		MessageServiceDeleteMessageProcedure,
		svc.DeleteMessage,
		connect.WithSchema(messageServiceMethods.ByName("DeleteMessage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/messages.v1.MessageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MessageServiceListConversationsProcedure:
			messageServiceListConversationsHandler.ServeHTTP(w, r)
		case MessageServiceCreateConversationProcedure:
			messageServiceCreateConversationHandler.ServeHTTP(w, r)
		case MessageServiceGetConversationProcedure:
			messageServiceGetConversationHandler.ServeHTTP(w, r)
		case MessageServiceListMessagesProcedure:
			messageServiceListMessagesHandler.ServeHTTP(w, r)
		case MessageServiceSendMessageProcedure:
			messageServiceSendMessageHandler.ServeHTTP(w, r)
		case MessageServiceMarkReadProcedure:
			messageServiceMarkReadHandler.ServeHTTP(w, r)
		case MessageServiceDeleteMessageProcedure:
			messageServiceDeleteMessageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMessageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMessageServiceHandler struct{}

func (UnimplementedMessageServiceHandler) ListConversations(context.Context, *connect.Request[v1.ListConversationsRequest]) (*connect.Response[v1.ListConversationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("messages.v1.MessageService.ListConversations is not implemented"))
}

func (UnimplementedMessageServiceHandler) CreateConversation(context.Context, *connect.Request[v1.CreateConversationRequest]) (*connect.Response[v1.Conversation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("messages.v1.MessageService.CreateConversation is not implemented"))
}

func (UnimplementedMessageServiceHandler) GetConversation(context.Context, *connect.Request[v1.GetConversationRequest]) (*connect.Response[v1.Conversation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("messages.v1.MessageService.GetConversation is not implemented"))
}

func (UnimplementedMessageServiceHandler) ListMessages(context.Context, *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("messages.v1.MessageService.ListMessages is not implemented"))
}

func (UnimplementedMessageServiceHandler) SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.Message], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("messages.v1.MessageService.SendMessage is not implemented"))
}

func (UnimplementedMessageServiceHandler) MarkRead(context.Context, *connect.Request[v1.MarkReadRequest]) (*connect.Response[v1.MarkReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("messages.v1.MessageService.MarkRead is not implemented"))
}

func (UnimplementedMessageServiceHandler) DeleteMessage(context.Context, *connect.Request[v1.DeleteMessageRequest]) (*connect.Response[v1.DeleteMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("messages.v1.MessageService.DeleteMessage is not implemented"))
}
