// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: dashboard/v1/dashboard.proto

package dashboardv1

import (
	v12 "github.com/kongken/ohome/pkg/proto/connections/v1"
	v11 "github.com/kongken/ohome/pkg/proto/posts/v1"
	v1 "github.com/kongken/ohome/pkg/proto/users/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{0}
}

type SummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Greeting      string                 `protobuf:"bytes,2,opt,name=greeting,proto3" json:"greeting,omitempty"`
	Subtitle      string                 `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResponse.ProtoReflect.Descriptor instead.
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *SummaryResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SummaryResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

func (x *SummaryResponse) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{2}
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // profile_views | post_impressions | new_followers
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	ChangePct     float64                `protobuf:"fixed64,3,opt,name=change_pct,json=changePct,proto3" json:"change_pct,omitempty"` // for trend cards
	ChangeAbs     int64                  `protobuf:"varint,4,opt,name=change_abs,json=changeAbs,proto3" json:"change_abs,omitempty"`  // for delta cards
	Period        string                 `protobuf:"bytes,5,opt,name=period,proto3" json:"period,omitempty"`                          // today | week | since_last_login
	Label         string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *Metric) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Metric) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetChangePct() float64 {
	if x != nil {
		return x.ChangePct
	}
	return 0
}

func (x *Metric) GetChangeAbs() int64 {
	if x != nil {
		return x.ChangeAbs
	}
	return 0
}

func (x *Metric) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Metric) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Metric              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	AnalyticsUrl  string                 `protobuf:"bytes,2,opt,name=analytics_url,json=analyticsUrl,proto3" json:"analytics_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsResponse) GetItems() []*Metric {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MetricsResponse) GetAnalyticsUrl() string {
	if x != nil {
		return x.AnalyticsUrl
	}
	return ""
}

type ActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityRequest) Reset() {
	*x = ActivityRequest{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityRequest) ProtoMessage() {}

func (x *ActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityRequest.ProtoReflect.Descriptor instead.
func (*ActivityRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *ActivityRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ActivityResponse struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	Posts              []*v11.Post              `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	ConnectionRequests []*v12.ConnectionRequest `protobuf:"bytes,2,rep,name=connection_requests,json=connectionRequests,proto3" json:"connection_requests,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ActivityResponse) Reset() {
	*x = ActivityResponse{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityResponse) ProtoMessage() {}

func (x *ActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityResponse.ProtoReflect.Descriptor instead.
func (*ActivityResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *ActivityResponse) GetPosts() []*v11.Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ActivityResponse) GetConnectionRequests() []*v12.ConnectionRequest {
	if x != nil {
		return x.ConnectionRequests
	}
	return nil
}

type QuickLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // events | market | articles | jobs
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuickLink) Reset() {
	*x = QuickLink{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickLink) ProtoMessage() {}

func (x *QuickLink) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickLink.ProtoReflect.Descriptor instead.
func (*QuickLink) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *QuickLink) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *QuickLink) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *QuickLink) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *QuickLink) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type QuickLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuickLinksRequest) Reset() {
	*x = QuickLinksRequest{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickLinksRequest) ProtoMessage() {}

func (x *QuickLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickLinksRequest.ProtoReflect.Descriptor instead.
func (*QuickLinksRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{8}
}

type QuickLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*QuickLink           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuickLinksResponse) Reset() {
	*x = QuickLinksResponse{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickLinksResponse) ProtoMessage() {}

func (x *QuickLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickLinksResponse.ProtoReflect.Descriptor instead.
func (*QuickLinksResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{9}
}

func (x *QuickLinksResponse) GetItems() []*QuickLink {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_dashboard_v1_dashboard_proto protoreflect.FileDescriptor

const file_dashboard_v1_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x1cdashboard/v1/dashboard.proto\x12\fdashboard.v1\x1a connections/v1/connections.proto\x1a\x14posts/v1/posts.proto\x1a\x14users/v1/users.proto\"\x10\n" +
	"\x0eSummaryRequest\"m\n" +
	"\x0fSummaryResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.users.v1.UserR\x04user\x12\x1a\n" +
	"\bgreeting\x18\x02 \x01(\tR\bgreeting\x12\x1a\n" +
	"\bsubtitle\x18\x03 \x01(\tR\bsubtitle\"\x10\n" +
	"\x0eMetricsRequest\"\x9c\x01\n" +
	"\x06Metric\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12\x1d\n" +
	"\n" +
	"change_pct\x18\x03 \x01(\x01R\tchangePct\x12\x1d\n" +
	"\n" +
	"change_abs\x18\x04 \x01(\x03R\tchangeAbs\x12\x16\n" +
	"\x06period\x18\x05 \x01(\tR\x06period\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\"b\n" +
	"\x0fMetricsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.dashboard.v1.MetricR\x05items\x12#\n" +
	"\ranalytics_url\x18\x02 \x01(\tR\fanalyticsUrl\"'\n" +
	"\x0fActivityRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\x8c\x01\n" +
	"\x10ActivityResponse\x12$\n" +
	"\x05posts\x18\x01 \x03(\v2\x0e.posts.v1.PostR\x05posts\x12R\n" +
	"\x13connection_requests\x18\x02 \x03(\v2!.connections.v1.ConnectionRequestR\x12connectionRequests\"Y\n" +
	"\tQuickLink\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"\x13\n" +
	"\x11QuickLinksRequest\"C\n" +
	"\x12QuickLinksResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.dashboard.v1.QuickLinkR\x05items2\xbe\x02\n" +
	"\x10DashboardService\x12F\n" +
	"\aSummary\x12\x1c.dashboard.v1.SummaryRequest\x1a\x1d.dashboard.v1.SummaryResponse\x12F\n" +
	"\aMetrics\x12\x1c.dashboard.v1.MetricsRequest\x1a\x1d.dashboard.v1.MetricsResponse\x12I\n" +
	"\bActivity\x12\x1d.dashboard.v1.ActivityRequest\x1a\x1e.dashboard.v1.ActivityResponse\x12O\n" +
	"\n" +
	"QuickLinks\x12\x1f.dashboard.v1.QuickLinksRequest\x1a .dashboard.v1.QuickLinksResponseB=Z;github.com/kongken/ohome/pkg/proto/dashboard/v1;dashboardv1b\x06proto3"

var (
	file_dashboard_v1_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_v1_dashboard_proto_rawDescData []byte
)

func file_dashboard_v1_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_v1_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_v1_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_v1_dashboard_proto_rawDesc), len(file_dashboard_v1_dashboard_proto_rawDesc)))
	})
	return file_dashboard_v1_dashboard_proto_rawDescData
}

var file_dashboard_v1_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_dashboard_v1_dashboard_proto_goTypes = []any{
	(*SummaryRequest)(nil),        // 0: dashboard.v1.SummaryRequest
	(*SummaryResponse)(nil),       // 1: dashboard.v1.SummaryResponse
	(*MetricsRequest)(nil),        // 2: dashboard.v1.MetricsRequest
	(*Metric)(nil),                // 3: dashboard.v1.Metric
	(*MetricsResponse)(nil),       // 4: dashboard.v1.MetricsResponse
	(*ActivityRequest)(nil),       // 5: dashboard.v1.ActivityRequest
	(*ActivityResponse)(nil),      // 6: dashboard.v1.ActivityResponse
	(*QuickLink)(nil),             // 7: dashboard.v1.QuickLink
	(*QuickLinksRequest)(nil),     // 8: dashboard.v1.QuickLinksRequest
	(*QuickLinksResponse)(nil),    // 9: dashboard.v1.QuickLinksResponse
	(*v1.User)(nil),               // 10: users.v1.User
	(*v11.Post)(nil),              // 11: posts.v1.Post
	(*v12.ConnectionRequest)(nil), // 12: connections.v1.ConnectionRequest
}
var file_dashboard_v1_dashboard_proto_depIdxs = []int32{
	10, // 0: dashboard.v1.SummaryResponse.user:type_name -> users.v1.User
	3,  // 1: dashboard.v1.MetricsResponse.items:type_name -> dashboard.v1.Metric
	11, // 2: dashboard.v1.ActivityResponse.posts:type_name -> posts.v1.Post
	12, // 3: dashboard.v1.ActivityResponse.connection_requests:type_name -> connections.v1.ConnectionRequest
	7,  // 4: dashboard.v1.QuickLinksResponse.items:type_name -> dashboard.v1.QuickLink
	0,  // 5: dashboard.v1.DashboardService.Summary:input_type -> dashboard.v1.SummaryRequest
	2,  // 6: dashboard.v1.DashboardService.Metrics:input_type -> dashboard.v1.MetricsRequest
	5,  // 7: dashboard.v1.DashboardService.Activity:input_type -> dashboard.v1.ActivityRequest
	8,  // 8: dashboard.v1.DashboardService.QuickLinks:input_type -> dashboard.v1.QuickLinksRequest
	1,  // 9: dashboard.v1.DashboardService.Summary:output_type -> dashboard.v1.SummaryResponse
	4,  // 10: dashboard.v1.DashboardService.Metrics:output_type -> dashboard.v1.MetricsResponse
	6,  // 11: dashboard.v1.DashboardService.Activity:output_type -> dashboard.v1.ActivityResponse
	9,  // 12: dashboard.v1.DashboardService.QuickLinks:output_type -> dashboard.v1.QuickLinksResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_dashboard_v1_dashboard_proto_init() }
func file_dashboard_v1_dashboard_proto_init() {
	if File_dashboard_v1_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_v1_dashboard_proto_rawDesc), len(file_dashboard_v1_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboard_v1_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_v1_dashboard_proto_depIdxs,
		MessageInfos:      file_dashboard_v1_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_v1_dashboard_proto = out.File
	file_dashboard_v1_dashboard_proto_goTypes = nil
	file_dashboard_v1_dashboard_proto_depIdxs = nil
}
