// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: notifications/v1/notifications.proto

package notificationsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kongken/ohome/pkg/proto/notifications/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotificationServiceName is the fully-qualified name of the NotificationService service.
	NotificationServiceName = "notifications.v1.NotificationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotificationServiceListProcedure is the fully-qualified name of the NotificationService's List
	// RPC.
	NotificationServiceListProcedure = "/notifications.v1.NotificationService/List"
	// NotificationServiceUnreadCountProcedure is the fully-qualified name of the NotificationService's
	// UnreadCount RPC.
	NotificationServiceUnreadCountProcedure = "/notifications.v1.NotificationService/UnreadCount"
	// NotificationServiceMarkReadProcedure is the fully-qualified name of the NotificationService's
	// MarkRead RPC.
	NotificationServiceMarkReadProcedure = "/notifications.v1.NotificationService/MarkRead"
	// NotificationServiceMarkAllReadProcedure is the fully-qualified name of the NotificationService's
	// MarkAllRead RPC.
	NotificationServiceMarkAllReadProcedure = "/notifications.v1.NotificationService/MarkAllRead"
	// NotificationServiceDeleteProcedure is the fully-qualified name of the NotificationService's
	// Delete RPC.
	NotificationServiceDeleteProcedure = "/notifications.v1.NotificationService/Delete"
)

// NotificationServiceClient is a client for the notifications.v1.NotificationService service.
type NotificationServiceClient interface {
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	UnreadCount(context.Context, *connect.Request[v1.UnreadCountRequest]) (*connect.Response[v1.UnreadCountResponse], error)
	MarkRead(context.Context, *connect.Request[v1.MarkReadRequest]) (*connect.Response[v1.MarkReadResponse], error)
	MarkAllRead(context.Context, *connect.Request[v1.MarkAllReadRequest]) (*connect.Response[v1.MarkAllReadResponse], error)
	Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error)
}

// NewNotificationServiceClient constructs a client for the notifications.v1.NotificationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotificationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotificationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notificationServiceMethods := v1.File_notifications_v1_notifications_proto.Services().ByName("NotificationService").Methods()
	return &notificationServiceClient{
		list: connect.NewClient[v1.ListRequest, v1.ListResponse](
			httpClient,
			baseURL+NotificationServiceListProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		unreadCount: connect.NewClient[v1.UnreadCountRequest, v1.UnreadCountResponse](
			httpClient,
			baseURL+NotificationServiceUnreadCountProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("UnreadCount")),
			connect.WithClientOptions(opts...),
		),
		markRead: connect.NewClient[v1.MarkReadRequest, v1.MarkReadResponse](
			httpClient,
			baseURL+NotificationServiceMarkReadProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("MarkRead")),
			connect.WithClientOptions(opts...),
		),
		markAllRead: connect.NewClient[v1.MarkAllReadRequest, v1.MarkAllReadResponse](
			httpClient,
			baseURL+NotificationServiceMarkAllReadProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("MarkAllRead")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.DeleteRequest, v1.DeleteResponse](
			httpClient,
			baseURL+NotificationServiceDeleteProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notificationServiceClient implements NotificationServiceClient.
type notificationServiceClient struct {
	list        *connect.Client[v1.ListRequest, v1.ListResponse]
	unreadCount *connect.Client[v1.UnreadCountRequest, v1.UnreadCountResponse]
	markRead    *connect.Client[v1.MarkReadRequest, v1.MarkReadResponse]
	markAllRead *connect.Client[v1.MarkAllReadRequest, v1.MarkAllReadResponse]
	delete      *connect.Client[v1.DeleteRequest, v1.DeleteResponse]
}

// List calls notifications.v1.NotificationService.List.
func (c *notificationServiceClient) List(ctx context.Context, req *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// UnreadCount calls notifications.v1.NotificationService.UnreadCount.
func (c *notificationServiceClient) UnreadCount(ctx context.Context, req *connect.Request[v1.UnreadCountRequest]) (*connect.Response[v1.UnreadCountResponse], error) {
	return c.unreadCount.CallUnary(ctx, req)
}

// MarkRead calls notifications.v1.NotificationService.MarkRead.
func (c *notificationServiceClient) MarkRead(ctx context.Context, req *connect.Request[v1.MarkReadRequest]) (*connect.Response[v1.MarkReadResponse], error) {
	return c.markRead.CallUnary(ctx, req)
}

// MarkAllRead calls notifications.v1.NotificationService.MarkAllRead.
func (c *notificationServiceClient) MarkAllRead(ctx context.Context, req *connect.Request[v1.MarkAllReadRequest]) (*connect.Response[v1.MarkAllReadResponse], error) {
	return c.markAllRead.CallUnary(ctx, req)
}

// Delete calls notifications.v1.NotificationService.Delete.
func (c *notificationServiceClient) Delete(ctx context.Context, req *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// NotificationServiceHandler is an implementation of the notifications.v1.NotificationService
// service.
type NotificationServiceHandler interface {
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	UnreadCount(context.Context, *connect.Request[v1.UnreadCountRequest]) (*connect.Response[v1.UnreadCountResponse], error)
	MarkRead(context.Context, *connect.Request[v1.MarkReadRequest]) (*connect.Response[v1.MarkReadResponse], error)
	MarkAllRead(context.Context, *connect.Request[v1.MarkAllReadRequest]) (*connect.Response[v1.MarkAllReadResponse], error)
	Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error)
}

// NewNotificationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotificationServiceHandler(svc NotificationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notificationServiceMethods := v1.File_notifications_v1_notifications_proto.Services().ByName("NotificationService").Methods()
	notificationServiceListHandler := connect.NewUnaryHandler(
		NotificationServiceListProcedure,
		svc.List,
		connect.WithSchema(notificationServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceUnreadCountHandler := connect.NewUnaryHandler(
		NotificationServiceUnreadCountProcedure,
		svc.UnreadCount,
		connect.WithSchema(notificationServiceMethods.ByName("UnreadCount")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceMarkReadHandler := connect.NewUnaryHandler(
		NotificationServiceMarkReadProcedure,
		svc.MarkRead,
		connect.WithSchema(notificationServiceMethods.ByName("MarkRead")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceMarkAllReadHandler := connect.NewUnaryHandler(
		NotificationServiceMarkAllReadProcedure,
		svc.MarkAllRead,
		connect.WithSchema(notificationServiceMethods.ByName("MarkAllRead")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceDeleteHandler := connect.NewUnaryHandler(
		NotificationServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(notificationServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	return "/notifications.v1.NotificationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotificationServiceListProcedure:
			notificationServiceListHandler.ServeHTTP(w, r)
		case NotificationServiceUnreadCountProcedure:
			notificationServiceUnreadCountHandler.ServeHTTP(w, r)
		case NotificationServiceMarkReadProcedure:
			notificationServiceMarkReadHandler.ServeHTTP(w, r)
		case NotificationServiceMarkAllReadProcedure:
			notificationServiceMarkAllReadHandler.ServeHTTP(w, r)
		case NotificationServiceDeleteProcedure:
			notificationServiceDeleteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotificationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotificationServiceHandler struct{}

func (UnimplementedNotificationServiceHandler) List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notifications.v1.NotificationService.List is not implemented"))
}

func (UnimplementedNotificationServiceHandler) UnreadCount(context.Context, *connect.Request[v1.UnreadCountRequest]) (*connect.Response[v1.UnreadCountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notifications.v1.NotificationService.UnreadCount is not implemented"))
}

func (UnimplementedNotificationServiceHandler) MarkRead(context.Context, *connect.Request[v1.MarkReadRequest]) (*connect.Response[v1.MarkReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notifications.v1.NotificationService.MarkRead is not implemented"))
}

func (UnimplementedNotificationServiceHandler) MarkAllRead(context.Context, *connect.Request[v1.MarkAllReadRequest]) (*connect.Response[v1.MarkAllReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notifications.v1.NotificationService.MarkAllRead is not implemented"))
}

func (UnimplementedNotificationServiceHandler) Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notifications.v1.NotificationService.Delete is not implemented"))
}
