// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: connections/v1/connections.proto

package connectionsv1

import (
	v11 "github.com/kongken/ohome/pkg/proto/common/v1"
	v1 "github.com/kongken/ohome/pkg/proto/users/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromUser      *v1.User               `protobuf:"bytes,2,opt,name=from_user,json=fromUser,proto3" json:"from_user,omitempty"`
	ToUser        *v1.User               `protobuf:"bytes,3,opt,name=to_user,json=toUser,proto3" json:"to_user,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // pending | accepted | rejected
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	mi := &file_connections_v1_connections_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectionRequest) GetFromUser() *v1.User {
	if x != nil {
		return x.FromUser
	}
	return nil
}

func (x *ConnectionRequest) GetToUser() *v1.User {
	if x != nil {
		return x.ToUser
	}
	return nil
}

func (x *ConnectionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConnectionRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_connections_v1_connections_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{1}
}

func (x *FollowRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_connections_v1_connections_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{2}
}

type UnfollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_connections_v1_connections_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UnfollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowResponse) Reset() {
	*x = UnfollowResponse{}
	mi := &file_connections_v1_connections_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResponse) ProtoMessage() {}

func (x *UnfollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResponse.ProtoReflect.Descriptor instead.
func (*UnfollowResponse) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{4}
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*v1.User             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          *v11.PageResponse      `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_connections_v1_connections_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersResponse) GetItems() []*v1.User {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListUsersResponse) GetPage() *v11.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Page          *v11.PageRequest       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowersRequest) Reset() {
	*x = ListFollowersRequest{}
	mi := &file_connections_v1_connections_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowersRequest) ProtoMessage() {}

func (x *ListFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowersRequest.ProtoReflect.Descriptor instead.
func (*ListFollowersRequest) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{6}
}

func (x *ListFollowersRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListFollowersRequest) GetPage() *v11.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Page          *v11.PageRequest       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingRequest) Reset() {
	*x = ListFollowingRequest{}
	mi := &file_connections_v1_connections_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingRequest) ProtoMessage() {}

func (x *ListFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingRequest.ProtoReflect.Descriptor instead.
func (*ListFollowingRequest) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{7}
}

func (x *ListFollowingRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListFollowingRequest) GetPage() *v11.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v11.PageRequest       `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectionsRequest) Reset() {
	*x = ListConnectionsRequest{}
	mi := &file_connections_v1_connections_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectionsRequest) ProtoMessage() {}

func (x *ListConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectionsRequest.ProtoReflect.Descriptor instead.
func (*ListConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{8}
}

func (x *ListConnectionsRequest) GetPage() *v11.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type RemoveConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveConnectionRequest) Reset() {
	*x = RemoveConnectionRequest{}
	mi := &file_connections_v1_connections_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveConnectionRequest) ProtoMessage() {}

func (x *RemoveConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveConnectionRequest.ProtoReflect.Descriptor instead.
func (*RemoveConnectionRequest) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveConnectionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveConnectionResponse) Reset() {
	*x = RemoveConnectionResponse{}
	mi := &file_connections_v1_connections_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveConnectionResponse) ProtoMessage() {}

func (x *RemoveConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveConnectionResponse.ProtoReflect.Descriptor instead.
func (*RemoveConnectionResponse) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{10}
}

type ListRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v11.PageRequest       `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsRequest) Reset() {
	*x = ListRequestsRequest{}
	mi := &file_connections_v1_connections_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsRequest) ProtoMessage() {}

func (x *ListRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListRequestsRequest) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{11}
}

func (x *ListRequestsRequest) GetPage() *v11.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConnectionRequest   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          *v11.PageResponse      `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsResponse) Reset() {
	*x = ListRequestsResponse{}
	mi := &file_connections_v1_connections_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsResponse) ProtoMessage() {}

func (x *ListRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListRequestsResponse) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{12}
}

func (x *ListRequestsResponse) GetItems() []*ConnectionRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListRequestsResponse) GetPage() *v11.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type CreateRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToUserId      string                 `protobuf:"bytes,1,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequestRequest) Reset() {
	*x = CreateRequestRequest{}
	mi := &file_connections_v1_connections_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestRequest) ProtoMessage() {}

func (x *CreateRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateRequestRequest) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRequestRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

type AcceptRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequestRequest) Reset() {
	*x = AcceptRequestRequest{}
	mi := &file_connections_v1_connections_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequestRequest) ProtoMessage() {}

func (x *AcceptRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequestRequest) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{14}
}

func (x *AcceptRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RejectRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequestRequest) Reset() {
	*x = RejectRequestRequest{}
	mi := &file_connections_v1_connections_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequestRequest) ProtoMessage() {}

func (x *RejectRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connections_v1_connections_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequestRequest.ProtoReflect.Descriptor instead.
func (*RejectRequestRequest) Descriptor() ([]byte, []int) {
	return file_connections_v1_connections_proto_rawDescGZIP(), []int{15}
}

func (x *RejectRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_connections_v1_connections_proto protoreflect.FileDescriptor

const file_connections_v1_connections_proto_rawDesc = "" +
	"\n" +
	" connections/v1/connections.proto\x12\x0econnections.v1\x1a\x15common/v1/types.proto\x1a\x14users/v1/users.proto\"\xb0\x01\n" +
	"\x11ConnectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\tfrom_user\x18\x02 \x01(\v2\x0e.users.v1.UserR\bfromUser\x12'\n" +
	"\ato_user\x18\x03 \x01(\v2\x0e.users.v1.UserR\x06toUser\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"+\n" +
	"\rFollowRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x10\n" +
	"\x0eFollowResponse\"-\n" +
	"\x0fUnfollowRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x12\n" +
	"\x10UnfollowResponse\"f\n" +
	"\x11ListUsersResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.users.v1.UserR\x05items\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.common.v1.PageResponseR\x04page\"^\n" +
	"\x14ListFollowersRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.common.v1.PageRequestR\x04page\"^\n" +
	"\x14ListFollowingRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.common.v1.PageRequestR\x04page\"D\n" +
	"\x16ListConnectionsRequest\x12*\n" +
	"\x04page\x18\x01 \x01(\v2\x16.common.v1.PageRequestR\x04page\"2\n" +
	"\x17RemoveConnectionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x1a\n" +
	"\x18RemoveConnectionResponse\"A\n" +
	"\x13ListRequestsRequest\x12*\n" +
	"\x04page\x18\x01 \x01(\v2\x16.common.v1.PageRequestR\x04page\"|\n" +
	"\x14ListRequestsResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.connections.v1.ConnectionRequestR\x05items\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.common.v1.PageResponseR\x04page\"4\n" +
	"\x14CreateRequestRequest\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x01 \x01(\tR\btoUserId\"&\n" +
	"\x14AcceptRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14RejectRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x8d\a\n" +
	"\x11ConnectionService\x12G\n" +
	"\x06Follow\x12\x1d.connections.v1.FollowRequest\x1a\x1e.connections.v1.FollowResponse\x12M\n" +
	"\bUnfollow\x12\x1f.connections.v1.UnfollowRequest\x1a .connections.v1.UnfollowResponse\x12X\n" +
	"\rListFollowers\x12$.connections.v1.ListFollowersRequest\x1a!.connections.v1.ListUsersResponse\x12X\n" +
	"\rListFollowing\x12$.connections.v1.ListFollowingRequest\x1a!.connections.v1.ListUsersResponse\x12\\\n" +
	"\x0fListConnections\x12&.connections.v1.ListConnectionsRequest\x1a!.connections.v1.ListUsersResponse\x12e\n" +
	"\x10RemoveConnection\x12'.connections.v1.RemoveConnectionRequest\x1a(.connections.v1.RemoveConnectionResponse\x12Y\n" +
	"\fListRequests\x12#.connections.v1.ListRequestsRequest\x1a$.connections.v1.ListRequestsResponse\x12X\n" +
	"\rCreateRequest\x12$.connections.v1.CreateRequestRequest\x1a!.connections.v1.ConnectionRequest\x12X\n" +
	"\rAcceptRequest\x12$.connections.v1.AcceptRequestRequest\x1a!.connections.v1.ConnectionRequest\x12X\n" +
	"\rRejectRequest\x12$.connections.v1.RejectRequestRequest\x1a!.connections.v1.ConnectionRequestBAZ?github.com/kongken/ohome/pkg/proto/connections/v1;connectionsv1b\x06proto3"

var (
	file_connections_v1_connections_proto_rawDescOnce sync.Once
	file_connections_v1_connections_proto_rawDescData []byte
)

func file_connections_v1_connections_proto_rawDescGZIP() []byte {
	file_connections_v1_connections_proto_rawDescOnce.Do(func() {
		file_connections_v1_connections_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connections_v1_connections_proto_rawDesc), len(file_connections_v1_connections_proto_rawDesc)))
	})
	return file_connections_v1_connections_proto_rawDescData
}

var file_connections_v1_connections_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_connections_v1_connections_proto_goTypes = []any{
	(*ConnectionRequest)(nil),        // 0: connections.v1.ConnectionRequest
	(*FollowRequest)(nil),            // 1: connections.v1.FollowRequest
	(*FollowResponse)(nil),           // 2: connections.v1.FollowResponse
	(*UnfollowRequest)(nil),          // 3: connections.v1.UnfollowRequest
	(*UnfollowResponse)(nil),         // 4: connections.v1.UnfollowResponse
	(*ListUsersResponse)(nil),        // 5: connections.v1.ListUsersResponse
	(*ListFollowersRequest)(nil),     // 6: connections.v1.ListFollowersRequest
	(*ListFollowingRequest)(nil),     // 7: connections.v1.ListFollowingRequest
	(*ListConnectionsRequest)(nil),   // 8: connections.v1.ListConnectionsRequest
	(*RemoveConnectionRequest)(nil),  // 9: connections.v1.RemoveConnectionRequest
	(*RemoveConnectionResponse)(nil), // 10: connections.v1.RemoveConnectionResponse
	(*ListRequestsRequest)(nil),      // 11: connections.v1.ListRequestsRequest
	(*ListRequestsResponse)(nil),     // 12: connections.v1.ListRequestsResponse
	(*CreateRequestRequest)(nil),     // 13: connections.v1.CreateRequestRequest
	(*AcceptRequestRequest)(nil),     // 14: connections.v1.AcceptRequestRequest
	(*RejectRequestRequest)(nil),     // 15: connections.v1.RejectRequestRequest
	(*v1.User)(nil),                  // 16: users.v1.User
	(*v11.PageResponse)(nil),         // 17: common.v1.PageResponse
	(*v11.PageRequest)(nil),          // 18: common.v1.PageRequest
}
var file_connections_v1_connections_proto_depIdxs = []int32{
	16, // 0: connections.v1.ConnectionRequest.from_user:type_name -> users.v1.User
	16, // 1: connections.v1.ConnectionRequest.to_user:type_name -> users.v1.User
	16, // 2: connections.v1.ListUsersResponse.items:type_name -> users.v1.User
	17, // 3: connections.v1.ListUsersResponse.page:type_name -> common.v1.PageResponse
	18, // 4: connections.v1.ListFollowersRequest.page:type_name -> common.v1.PageRequest
	18, // 5: connections.v1.ListFollowingRequest.page:type_name -> common.v1.PageRequest
	18, // 6: connections.v1.ListConnectionsRequest.page:type_name -> common.v1.PageRequest
	18, // 7: connections.v1.ListRequestsRequest.page:type_name -> common.v1.PageRequest
	0,  // 8: connections.v1.ListRequestsResponse.items:type_name -> connections.v1.ConnectionRequest
	17, // 9: connections.v1.ListRequestsResponse.page:type_name -> common.v1.PageResponse
	1,  // 10: connections.v1.ConnectionService.Follow:input_type -> connections.v1.FollowRequest
	3,  // 11: connections.v1.ConnectionService.Unfollow:input_type -> connections.v1.UnfollowRequest
	6,  // 12: connections.v1.ConnectionService.ListFollowers:input_type -> connections.v1.ListFollowersRequest
	7,  // 13: connections.v1.ConnectionService.ListFollowing:input_type -> connections.v1.ListFollowingRequest
	8,  // 14: connections.v1.ConnectionService.ListConnections:input_type -> connections.v1.ListConnectionsRequest
	9,  // 15: connections.v1.ConnectionService.RemoveConnection:input_type -> connections.v1.RemoveConnectionRequest
	11, // 16: connections.v1.ConnectionService.ListRequests:input_type -> connections.v1.ListRequestsRequest
	13, // 17: connections.v1.ConnectionService.CreateRequest:input_type -> connections.v1.CreateRequestRequest
	14, // 18: connections.v1.ConnectionService.AcceptRequest:input_type -> connections.v1.AcceptRequestRequest
	15, // 19: connections.v1.ConnectionService.RejectRequest:input_type -> connections.v1.RejectRequestRequest
	2,  // 20: connections.v1.ConnectionService.Follow:output_type -> connections.v1.FollowResponse
	4,  // 21: connections.v1.ConnectionService.Unfollow:output_type -> connections.v1.UnfollowResponse
	5,  // 22: connections.v1.ConnectionService.ListFollowers:output_type -> connections.v1.ListUsersResponse
	5,  // 23: connections.v1.ConnectionService.ListFollowing:output_type -> connections.v1.ListUsersResponse
	5,  // 24: connections.v1.ConnectionService.ListConnections:output_type -> connections.v1.ListUsersResponse
	10, // 25: connections.v1.ConnectionService.RemoveConnection:output_type -> connections.v1.RemoveConnectionResponse
	12, // 26: connections.v1.ConnectionService.ListRequests:output_type -> connections.v1.ListRequestsResponse
	0,  // 27: connections.v1.ConnectionService.CreateRequest:output_type -> connections.v1.ConnectionRequest
	0,  // 28: connections.v1.ConnectionService.AcceptRequest:output_type -> connections.v1.ConnectionRequest
	0,  // 29: connections.v1.ConnectionService.RejectRequest:output_type -> connections.v1.ConnectionRequest
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_connections_v1_connections_proto_init() }
func file_connections_v1_connections_proto_init() {
	if File_connections_v1_connections_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connections_v1_connections_proto_rawDesc), len(file_connections_v1_connections_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connections_v1_connections_proto_goTypes,
		DependencyIndexes: file_connections_v1_connections_proto_depIdxs,
		MessageInfos:      file_connections_v1_connections_proto_msgTypes,
	}.Build()
	File_connections_v1_connections_proto = out.File
	file_connections_v1_connections_proto_goTypes = nil
	file_connections_v1_connections_proto_depIdxs = nil
}
