// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: connections/v1/connections.proto

package connectionsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kongken/ohome/pkg/proto/connections/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConnectionServiceName is the fully-qualified name of the ConnectionService service.
	ConnectionServiceName = "connections.v1.ConnectionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConnectionServiceFollowProcedure is the fully-qualified name of the ConnectionService's Follow
	// RPC.
	ConnectionServiceFollowProcedure = "/connections.v1.ConnectionService/Follow"
	// ConnectionServiceUnfollowProcedure is the fully-qualified name of the ConnectionService's
	// Unfollow RPC.
	ConnectionServiceUnfollowProcedure = "/connections.v1.ConnectionService/Unfollow"
	// ConnectionServiceListFollowersProcedure is the fully-qualified name of the ConnectionService's
	// ListFollowers RPC.
	ConnectionServiceListFollowersProcedure = "/connections.v1.ConnectionService/ListFollowers"
	// ConnectionServiceListFollowingProcedure is the fully-qualified name of the ConnectionService's
	// ListFollowing RPC.
	ConnectionServiceListFollowingProcedure = "/connections.v1.ConnectionService/ListFollowing"
	// ConnectionServiceListConnectionsProcedure is the fully-qualified name of the ConnectionService's
	// ListConnections RPC.
	ConnectionServiceListConnectionsProcedure = "/connections.v1.ConnectionService/ListConnections"
	// ConnectionServiceRemoveConnectionProcedure is the fully-qualified name of the ConnectionService's
	// RemoveConnection RPC.
	ConnectionServiceRemoveConnectionProcedure = "/connections.v1.ConnectionService/RemoveConnection"
	// ConnectionServiceListRequestsProcedure is the fully-qualified name of the ConnectionService's
	// ListRequests RPC.
	ConnectionServiceListRequestsProcedure = "/connections.v1.ConnectionService/ListRequests"
	// ConnectionServiceCreateRequestProcedure is the fully-qualified name of the ConnectionService's
	// CreateRequest RPC.
	ConnectionServiceCreateRequestProcedure = "/connections.v1.ConnectionService/CreateRequest"
	// ConnectionServiceAcceptRequestProcedure is the fully-qualified name of the ConnectionService's
	// AcceptRequest RPC.
	ConnectionServiceAcceptRequestProcedure = "/connections.v1.ConnectionService/AcceptRequest"
	// ConnectionServiceRejectRequestProcedure is the fully-qualified name of the ConnectionService's
	// RejectRequest RPC.
	ConnectionServiceRejectRequestProcedure = "/connections.v1.ConnectionService/RejectRequest"
)

// ConnectionServiceClient is a client for the connections.v1.ConnectionService service.
type ConnectionServiceClient interface {
	Follow(context.Context, *connect.Request[v1.FollowRequest]) (*connect.Response[v1.FollowResponse], error)
	Unfollow(context.Context, *connect.Request[v1.UnfollowRequest]) (*connect.Response[v1.UnfollowResponse], error)
	ListFollowers(context.Context, *connect.Request[v1.ListFollowersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	ListFollowing(context.Context, *connect.Request[v1.ListFollowingRequest]) (*connect.Response[v1.ListUsersResponse], error)
	ListConnections(context.Context, *connect.Request[v1.ListConnectionsRequest]) (*connect.Response[v1.ListUsersResponse], error)
	RemoveConnection(context.Context, *connect.Request[v1.RemoveConnectionRequest]) (*connect.Response[v1.RemoveConnectionResponse], error)
	ListRequests(context.Context, *connect.Request[v1.ListRequestsRequest]) (*connect.Response[v1.ListRequestsResponse], error)
	CreateRequest(context.Context, *connect.Request[v1.CreateRequestRequest]) (*connect.Response[v1.ConnectionRequest], error)
	AcceptRequest(context.Context, *connect.Request[v1.AcceptRequestRequest]) (*connect.Response[v1.ConnectionRequest], error)
	RejectRequest(context.Context, *connect.Request[v1.RejectRequestRequest]) (*connect.Response[v1.ConnectionRequest], error)
}

// NewConnectionServiceClient constructs a client for the connections.v1.ConnectionService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConnectionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConnectionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	connectionServiceMethods := v1.File_connections_v1_connections_proto.Services().ByName("ConnectionService").Methods()
	return &connectionServiceClient{
		follow: connect.NewClient[v1.FollowRequest, v1.FollowResponse](
			httpClient,
			baseURL+ConnectionServiceFollowProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("Follow")),
			connect.WithClientOptions(opts...),
		),
		unfollow: connect.NewClient[v1.UnfollowRequest, v1.UnfollowResponse](
			httpClient,
			baseURL+ConnectionServiceUnfollowProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("Unfollow")),
			connect.WithClientOptions(opts...),
		),
		listFollowers: connect.NewClient[v1.ListFollowersRequest, v1.ListUsersResponse](
			httpClient,
			baseURL+ConnectionServiceListFollowersProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("ListFollowers")),
			connect.WithClientOptions(opts...),
		),
		listFollowing: connect.NewClient[v1.ListFollowingRequest, v1.ListUsersResponse](
			httpClient,
			baseURL+ConnectionServiceListFollowingProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("ListFollowing")),
			connect.WithClientOptions(opts...),
		),
		listConnections: connect.NewClient[v1.ListConnectionsRequest, v1.ListUsersResponse](
			httpClient,
			baseURL+ConnectionServiceListConnectionsProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("ListConnections")),
			connect.WithClientOptions(opts...),
		),
		removeConnection: connect.NewClient[v1.RemoveConnectionRequest, v1.RemoveConnectionResponse](
			httpClient,
			baseURL+ConnectionServiceRemoveConnectionProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("RemoveConnection")),
			connect.WithClientOptions(opts...),
		),
		listRequests: connect.NewClient[v1.ListRequestsRequest, v1.ListRequestsResponse](
			httpClient,
			baseURL+ConnectionServiceListRequestsProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("ListRequests")),
			connect.WithClientOptions(opts...),
		),
		createRequest: connect.NewClient[v1.CreateRequestRequest, v1.ConnectionRequest](
			httpClient,
			baseURL+ConnectionServiceCreateRequestProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("CreateRequest")),
			connect.WithClientOptions(opts...),
		),
		acceptRequest: connect.NewClient[v1.AcceptRequestRequest, v1.ConnectionRequest](
			httpClient,
			baseURL+ConnectionServiceAcceptRequestProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("AcceptRequest")),
			connect.WithClientOptions(opts...),
		),
		rejectRequest: connect.NewClient[v1.RejectRequestRequest, v1.ConnectionRequest](
			httpClient,
			baseURL+ConnectionServiceRejectRequestProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("RejectRequest")),
			connect.WithClientOptions(opts...),
		),
	}
}

// connectionServiceClient implements ConnectionServiceClient.
type connectionServiceClient struct {
	follow           *connect.Client[v1.FollowRequest, v1.FollowResponse]
	unfollow         *connect.Client[v1.UnfollowRequest, v1.UnfollowResponse]
	listFollowers    *connect.Client[v1.ListFollowersRequest, v1.ListUsersResponse]
	listFollowing    *connect.Client[v1.ListFollowingRequest, v1.ListUsersResponse]
	listConnections  *connect.Client[v1.ListConnectionsRequest, v1.ListUsersResponse]
	removeConnection *connect.Client[v1.RemoveConnectionRequest, v1.RemoveConnectionResponse]
	listRequests     *connect.Client[v1.ListRequestsRequest, v1.ListRequestsResponse]
	createRequest    *connect.Client[v1.CreateRequestRequest, v1.ConnectionRequest]
	acceptRequest    *connect.Client[v1.AcceptRequestRequest, v1.ConnectionRequest]
	rejectRequest    *connect.Client[v1.RejectRequestRequest, v1.ConnectionRequest]
}

// Follow calls connections.v1.ConnectionService.Follow.
func (c *connectionServiceClient) Follow(ctx context.Context, req *connect.Request[v1.FollowRequest]) (*connect.Response[v1.FollowResponse], error) {
	return c.follow.CallUnary(ctx, req)
}

// Unfollow calls connections.v1.ConnectionService.Unfollow.
func (c *connectionServiceClient) Unfollow(ctx context.Context, req *connect.Request[v1.UnfollowRequest]) (*connect.Response[v1.UnfollowResponse], error) {
	return c.unfollow.CallUnary(ctx, req)
}

// ListFollowers calls connections.v1.ConnectionService.ListFollowers.
func (c *connectionServiceClient) ListFollowers(ctx context.Context, req *connect.Request[v1.ListFollowersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return c.listFollowers.CallUnary(ctx, req)
}

// ListFollowing calls connections.v1.ConnectionService.ListFollowing.
func (c *connectionServiceClient) ListFollowing(ctx context.Context, req *connect.Request[v1.ListFollowingRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return c.listFollowing.CallUnary(ctx, req)
}

// ListConnections calls connections.v1.ConnectionService.ListConnections.
func (c *connectionServiceClient) ListConnections(ctx context.Context, req *connect.Request[v1.ListConnectionsRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return c.listConnections.CallUnary(ctx, req)
}

// RemoveConnection calls connections.v1.ConnectionService.RemoveConnection.
func (c *connectionServiceClient) RemoveConnection(ctx context.Context, req *connect.Request[v1.RemoveConnectionRequest]) (*connect.Response[v1.RemoveConnectionResponse], error) {
	return c.removeConnection.CallUnary(ctx, req)
}

// ListRequests calls connections.v1.ConnectionService.ListRequests.
func (c *connectionServiceClient) ListRequests(ctx context.Context, req *connect.Request[v1.ListRequestsRequest]) (*connect.Response[v1.ListRequestsResponse], error) {
	return c.listRequests.CallUnary(ctx, req)
}

// CreateRequest calls connections.v1.ConnectionService.CreateRequest.
func (c *connectionServiceClient) CreateRequest(ctx context.Context, req *connect.Request[v1.CreateRequestRequest]) (*connect.Response[v1.ConnectionRequest], error) {
	return c.createRequest.CallUnary(ctx, req)
}

// AcceptRequest calls connections.v1.ConnectionService.AcceptRequest.
func (c *connectionServiceClient) AcceptRequest(ctx context.Context, req *connect.Request[v1.AcceptRequestRequest]) (*connect.Response[v1.ConnectionRequest], error) {
	return c.acceptRequest.CallUnary(ctx, req)
}

// RejectRequest calls connections.v1.ConnectionService.RejectRequest.
func (c *connectionServiceClient) RejectRequest(ctx context.Context, req *connect.Request[v1.RejectRequestRequest]) (*connect.Response[v1.ConnectionRequest], error) {
	return c.rejectRequest.CallUnary(ctx, req)
}

// ConnectionServiceHandler is an implementation of the connections.v1.ConnectionService service.
type ConnectionServiceHandler interface {
	Follow(context.Context, *connect.Request[v1.FollowRequest]) (*connect.Response[v1.FollowResponse], error)
	Unfollow(context.Context, *connect.Request[v1.UnfollowRequest]) (*connect.Response[v1.UnfollowResponse], error)
	ListFollowers(context.Context, *connect.Request[v1.ListFollowersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	ListFollowing(context.Context, *connect.Request[v1.ListFollowingRequest]) (*connect.Response[v1.ListUsersResponse], error)
	ListConnections(context.Context, *connect.Request[v1.ListConnectionsRequest]) (*connect.Response[v1.ListUsersResponse], error)
	RemoveConnection(context.Context, *connect.Request[v1.RemoveConnectionRequest]) (*connect.Response[v1.RemoveConnectionResponse], error)
	ListRequests(context.Context, *connect.Request[v1.ListRequestsRequest]) (*connect.Response[v1.ListRequestsResponse], error)
	CreateRequest(context.Context, *connect.Request[v1.CreateRequestRequest]) (*connect.Response[v1.ConnectionRequest], error)
	AcceptRequest(context.Context, *connect.Request[v1.AcceptRequestRequest]) (*connect.Response[v1.ConnectionRequest], error)
	RejectRequest(context.Context, *connect.Request[v1.RejectRequestRequest]) (*connect.Response[v1.ConnectionRequest], error)
}

// NewConnectionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConnectionServiceHandler(svc ConnectionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	connectionServiceMethods := v1.File_connections_v1_connections_proto.Services().ByName("ConnectionService").Methods()
	connectionServiceFollowHandler := connect.NewUnaryHandler(
		ConnectionServiceFollowProcedure,
		svc.Follow,
		connect.WithSchema(connectionServiceMethods.ByName("Follow")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceUnfollowHandler := connect.NewUnaryHandler(
		ConnectionServiceUnfollowProcedure,
		svc.Unfollow,
		connect.WithSchema(connectionServiceMethods.ByName("Unfollow")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceListFollowersHandler := connect.NewUnaryHandler(
		ConnectionServiceListFollowersProcedure,
		svc.ListFollowers,
		connect.WithSchema(connectionServiceMethods.ByName("ListFollowers")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceListFollowingHandler := connect.NewUnaryHandler(
		ConnectionServiceListFollowingProcedure,
		svc.ListFollowing,
		connect.WithSchema(connectionServiceMethods.ByName("ListFollowing")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceListConnectionsHandler := connect.NewUnaryHandler(
		ConnectionServiceListConnectionsProcedure,
		svc.ListConnections,
		connect.WithSchema(connectionServiceMethods.ByName("ListConnections")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceRemoveConnectionHandler := connect.NewUnaryHandler(
		ConnectionServiceRemoveConnectionProcedure,
		svc.RemoveConnection,
		connect.WithSchema(connectionServiceMethods.ByName("RemoveConnection")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceListRequestsHandler := connect.NewUnaryHandler(
		ConnectionServiceListRequestsProcedure,
		svc.ListRequests,
		connect.WithSchema(connectionServiceMethods.ByName("ListRequests")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceCreateRequestHandler := connect.NewUnaryHandler(
		ConnectionServiceCreateRequestProcedure,
		svc.CreateRequest,
		connect.WithSchema(connectionServiceMethods.ByName("CreateRequest")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceAcceptRequestHandler := connect.NewUnaryHandler(
		ConnectionServiceAcceptRequestProcedure,
		svc.AcceptRequest,
		connect.WithSchema(connectionServiceMethods.ByName("AcceptRequest")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceRejectRequestHandler := connect.NewUnaryHandler(
		ConnectionServiceRejectRequestProcedure,
		svc.RejectRequest,
		connect.WithSchema(connectionServiceMethods.ByName("RejectRequest")),
		connect.WithHandlerOptions(opts...),
	)
	return "/connections.v1.ConnectionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConnectionServiceFollowProcedure:
			connectionServiceFollowHandler.ServeHTTP(w, r)
		case ConnectionServiceUnfollowProcedure:
			connectionServiceUnfollowHandler.ServeHTTP(w, r)
		case ConnectionServiceListFollowersProcedure:
			connectionServiceListFollowersHandler.ServeHTTP(w, r)
		case ConnectionServiceListFollowingProcedure:
			connectionServiceListFollowingHandler.ServeHTTP(w, r)
		case ConnectionServiceListConnectionsProcedure:
			connectionServiceListConnectionsHandler.ServeHTTP(w, r)
		case ConnectionServiceRemoveConnectionProcedure:
			connectionServiceRemoveConnectionHandler.ServeHTTP(w, r)
		case ConnectionServiceListRequestsProcedure:
			connectionServiceListRequestsHandler.ServeHTTP(w, r)
		case ConnectionServiceCreateRequestProcedure:
			connectionServiceCreateRequestHandler.ServeHTTP(w, r)
		case ConnectionServiceAcceptRequestProcedure:
			connectionServiceAcceptRequestHandler.ServeHTTP(w, r)
		case ConnectionServiceRejectRequestProcedure:
			connectionServiceRejectRequestHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConnectionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConnectionServiceHandler struct{}

func (UnimplementedConnectionServiceHandler) Follow(context.Context, *connect.Request[v1.FollowRequest]) (*connect.Response[v1.FollowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connections.v1.ConnectionService.Follow is not implemented"))
}

func (UnimplementedConnectionServiceHandler) Unfollow(context.Context, *connect.Request[v1.UnfollowRequest]) (*connect.Response[v1.UnfollowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connections.v1.ConnectionService.Unfollow is not implemented"))
}

func (UnimplementedConnectionServiceHandler) ListFollowers(context.Context, *connect.Request[v1.ListFollowersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connections.v1.ConnectionService.ListFollowers is not implemented"))
}

func (UnimplementedConnectionServiceHandler) ListFollowing(context.Context, *connect.Request[v1.ListFollowingRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connections.v1.ConnectionService.ListFollowing is not implemented"))
}

func (UnimplementedConnectionServiceHandler) ListConnections(context.Context, *connect.Request[v1.ListConnectionsRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connections.v1.ConnectionService.ListConnections is not implemented"))
}

func (UnimplementedConnectionServiceHandler) RemoveConnection(context.Context, *connect.Request[v1.RemoveConnectionRequest]) (*connect.Response[v1.RemoveConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connections.v1.ConnectionService.RemoveConnection is not implemented"))
}

func (UnimplementedConnectionServiceHandler) ListRequests(context.Context, *connect.Request[v1.ListRequestsRequest]) (*connect.Response[v1.ListRequestsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connections.v1.ConnectionService.ListRequests is not implemented"))
}

func (UnimplementedConnectionServiceHandler) CreateRequest(context.Context, *connect.Request[v1.CreateRequestRequest]) (*connect.Response[v1.ConnectionRequest], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connections.v1.ConnectionService.CreateRequest is not implemented"))
}

func (UnimplementedConnectionServiceHandler) AcceptRequest(context.Context, *connect.Request[v1.AcceptRequestRequest]) (*connect.Response[v1.ConnectionRequest], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connections.v1.ConnectionService.AcceptRequest is not implemented"))
}

func (UnimplementedConnectionServiceHandler) RejectRequest(context.Context, *connect.Request[v1.RejectRequestRequest]) (*connect.Response[v1.ConnectionRequest], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connections.v1.ConnectionService.RejectRequest is not implemented"))
}
