// Code generated by ent, DO NOT EDIT.

package commentlike

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/kongken/ohome/internal/dao/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldContainsFold(FieldID, id))
}

// CommentID applies equality check predicate on the "comment_id" field. It's identical to CommentIDEQ.
func CommentID(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldCommentID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldCreatedAt, v))
}

// CommentIDEQ applies the EQ predicate on the "comment_id" field.
func CommentIDEQ(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldCommentID, v))
}

// CommentIDNEQ applies the NEQ predicate on the "comment_id" field.
func CommentIDNEQ(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNEQ(FieldCommentID, v))
}

// CommentIDIn applies the In predicate on the "comment_id" field.
func CommentIDIn(vs ...string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldIn(FieldCommentID, vs...))
}

// CommentIDNotIn applies the NotIn predicate on the "comment_id" field.
func CommentIDNotIn(vs ...string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNotIn(FieldCommentID, vs...))
}

// CommentIDGT applies the GT predicate on the "comment_id" field.
func CommentIDGT(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGT(FieldCommentID, v))
}

// CommentIDGTE applies the GTE predicate on the "comment_id" field.
func CommentIDGTE(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGTE(FieldCommentID, v))
}

// CommentIDLT applies the LT predicate on the "comment_id" field.
func CommentIDLT(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLT(FieldCommentID, v))
}

// CommentIDLTE applies the LTE predicate on the "comment_id" field.
func CommentIDLTE(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLTE(FieldCommentID, v))
}

// CommentIDContains applies the Contains predicate on the "comment_id" field.
func CommentIDContains(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldContains(FieldCommentID, v))
}

// CommentIDHasPrefix applies the HasPrefix predicate on the "comment_id" field.
func CommentIDHasPrefix(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldHasPrefix(FieldCommentID, v))
}

// CommentIDHasSuffix applies the HasSuffix predicate on the "comment_id" field.
func CommentIDHasSuffix(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldHasSuffix(FieldCommentID, v))
}

// CommentIDEqualFold applies the EqualFold predicate on the "comment_id" field.
func CommentIDEqualFold(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEqualFold(FieldCommentID, v))
}

// CommentIDContainsFold applies the ContainsFold predicate on the "comment_id" field.
func CommentIDContainsFold(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldContainsFold(FieldCommentID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldContainsFold(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CommentLike) predicate.CommentLike {
	return predicate.CommentLike(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CommentLike) predicate.CommentLike {
	return predicate.CommentLike(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CommentLike) predicate.CommentLike {
	return predicate.CommentLike(sql.NotPredicates(p))
}
